spring:
  application:
    name: cpm-parking
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#        namespace: 43ea2193-6bb0-4aa6-9d17-2111e14b404e
        register-enabled: true
  datasource:
    url: jdbc:mysql://192.168.232.130:3306/cpm_parking?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.232.130
    port: 6379
  rabbitmq:
    host: 192.168.232.130
    port: 5672
    username: guest
    password: guest
    virtual-host: my_vhost
    publisher-confirm-type: correlated #correlated 异步回调，定义ConfirmCallback，MQ返回结果时会回调这个ConfirmCallback
    publisher-returns: false #开启publish-return功能，同样是基于callback机制，需要定义ReturnCallback
    template:
      mandatory: false #定义消息路由失败时的策略。true，则调用ReturnCallback；false：则直接丢弃消息
    listener:
      simple:
        acknowledge-mode: none #出现异常时返回unack，消息回滚到mq；没有异常，返回ack ,manual:手动控制,none:丢弃消息，不回滚到mq
        retry:
          enabled: true #开启消费者失败重试
          initial-interval: 1000ms #初识的失败等待时长为1秒
          multiplier: 1 #失败的等待时长倍数，下次等待时长 = multiplier * last-interval
          max-attempts: 3 #最大重试次数
          stateless: true #true无状态；false有状态。如果业务中包含事务，这里改为false
server:
  port: 10001
#日志配置文件
logging:
  config: classpath:log4j2-dev.xml
#接口文档，访问路径http://localhost:10001/swagger-ui.html
swagger:
  title: "智慧停车停车业务管理模块"
  description: "对停车业务进行管理"
  base-package: com.ustcsse.parking
  enabled: true
  version: 1.0.0
mybatis-plus:
  mapper-locations: classpath*:/com/ustcsse/parking/mapper/*.xml
